name: Docker Image CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . -t lana-baidu
          docker tag lana-baidu ${{ secrets.DOCKER_USERNAME }}/lana-baidu:${{ github.sha }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/lana-baidu
    build_armv7:
      runs-on: ubuntu-18.04
      name: Build on ARMv7
      steps:
        - uses: actions/checkout@v1.0.0
        - uses: uraimo/run-on-arch-action@v1.0.5
          id: runcmd
          with:
            architecture: armv7
            distribution: ubuntu18.04
            run: |
              docker build . -t lana-baidu
              docker tag lana-baidu ${{ secrets.DOCKER_USERNAME }}/lana-baidu:armv7-${{ github.sha }}
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              docker push ${{ secrets.DOCKER_USERNAME }}/lana-baidu