name: Docker Image CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . -t lana-baidu
          docker tag lana-baidu ${{ secrets.DOCKER_USERNAME }}/lana-baidu:${{ github.sha }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/lana-baidu